# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  PutSiteOnEC2:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3

      - name: Build
        run: hugo --minify
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::808122334604:role/github-portfolio
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Put site on S3 and generate presigned URL
        run: |
          pwd
          echo "${{ github.workspace }}"
          tar -czvf build.tar.gz .
          aws s3 cp build.tar.gz s3://static-site-staging-s3-808122334604-eu-central-1-an/build.tar.gz

          PRESIGNED_URL=$(aws s3 presign s3://static-site-staging-s3-808122334604-eu-central-1-an/build.tar.gz --expires-in 200)

          echo "::add-mask::$PRESIGNED_URL"
          echo "URL=$PRESIGNED_URL" >> $GITHUB_ENV
        working-directory: ${{ github.workspace }}/public/

      - name: Get instance ID
        run: >
          echo "EC2_INSTANCE=$(aws ec2 describe-instances
          --filter "Name=tag:Name,Values=static-site-ec2"
          --query "Reservations[0].Instances[0].InstanceId"
          --output text)" >> $GITHUB_ENV

      - name: Deploy site on instance
        run: |
          aws ssm send-command \
            --instance-ids "${{ env.EC2_INSTANCE }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              " cd /srv/static-site/content/"
              "curl -sLO \"${{ env.URL }}\"" 
              "tar -xzvf build.tar.gz"
              "rm build.tar.gz"
            ]}' \
            --comment "Deploying from S3"
